// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./database/prisma/schema.prisma",
  migrations: {
    path: "./database/prisma/migrations",
    seed: "node database/prisma/seeder/product.js"
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "mysql://root:@localhost:3306/belajar-express",
  },
});
